Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "AutoAddGPU" "false"
    Option "AllowMouseOpenFail" "true"
    Option "DontVTSwitch" "true"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection

Section "Module"
    Disable "glx"
EndSection

Section "Files"
    FontPath "/usr/share/fonts/misc"
EndSection

Section "Device"
    Identifier "AxiomFramebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "AxiomMonitor"
EndSection

Section "Screen"
    Identifier "AxiomScreen"
    Device "AxiomFramebuffer"
    Monitor "AxiomMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
    EndSubSection
EndSection

Section "InputDevice"
    Identifier "AxiomKeyboard"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
    Option "XkbLayout" "us"
    Option "CoreKeyboard" "true"
EndSection

Section "InputDevice"
    Identifier "AxiomMouse"
    Driver "evdev"
    Option "Device" "/dev/input/event1"
    Option "CorePointer" "true"
EndSection

Section "ServerLayout"
    Identifier "AxiomDesktop"
    Screen "AxiomScreen"
    InputDevice "AxiomKeyboard" "CoreKeyboard"
    InputDevice "AxiomMouse" "CorePointer"
EndSection
